#!/bin/sh
# this script is expected to be started thusly:
# wget -O - https://raw.githubusercontent.com/nihildeb/alpi/master/install |sh
set -e

ALPI_VERSION="0.0.1"
ALPINE_VERSION="$(cat /etc/alpine-release)"

echo "alpi v.${ALPI_VERSION}"
echo "alpine release ${ALPINE_VERSION}"

apk update
apk upgrade

packages='openssl git make'
for pkg in $packages ; do
  apk add "$pkg"
done

git clone https://github.com/nihildeb/alpi.git /alpi
cd /alpi
make

