#!/bin/sh
# this script is expected to be started thusly:
# wget -O - https://raw.githubusercontent.com/nihildeb/alpi/master/install |sh
set -e

VERSION="0.0.1"
ALPINE_VERSION="$(cat /etc/alpine-release)"

echo "alpi v.${VERSION}"
echo "alpine release ${ALPINE_VERSION}"

if [ -d /etc/alpi ]; then
  echo "alpi found, fucking DELETE this shit"
  rm -rf /etc/alpi
fi

if [ -d /etc/alpi ]; then
  echo 'fucking hell'
  exit 1
fi


packages='openssl vim git nginx'
for pkg in $packages ; do
  apk add --no-cache "$pkg"
done

if [ ! -d /etc/alpi ]; then
  echo "no alpi, cloning"
  cd /etc
  git clone https://github.com/nihildeb/alpi.git /etc/alpi
fi

ln -sf /etc/alpi/init.d/alpi.sh /etc/init.d/alpi
ln -sf /etc/alpi/profile.d/* /etc/profile.d/
lbu ci -v -d
reboot

